apps/idos-data-dashboard/package.json, apps/idos-enclave/src/enclave.js, apps/idos-example-dapp/index.html, apps/idos-example-dapp/package.json, apps/idos-example-dapp/src/main.js, apps/idos-example-dapp/vite.config.ts, packages/idos-sdk-js/package.json, packages/idos-sdk-js/src/lib/auth.js, packages/idos-sdk-js/src/lib/data.js, packages/idos-sdk-js/src/lib/kwil-wrapper.js, pnpm-lock.yaml
@ditoglez: no need to merge this since it'd probably be hell with your WIP changes; just leaving it here to pick from it in the future
=> Integration example for NEAR wallets. Also: update kwil-js dependency; use kwil's new description method; example-dapp+SDK+enclave cleanup

packages/idos-sdk-js/src/lib/enclave-providers/iframe-enclave.js
Top of my head, not sure if right.
=> One less teleport promise

packages/idos-sdk-js/src/lib/auth.js, packages/idos-sdk-js/src/lib/crypto.js, packages/idos-sdk-js/src/lib/data.js, packages/idos-sdk-js/src/lib/enclave-providers/enclave-provider.js, packages/idos-sdk-js/src/lib/grants/evm.js, packages/idos-sdk-js/src/lib/kwil-wrapper.js, packages/idos-sdk-js/src/lib/verifiable-credentials.js
=> Fix lint nits

apps/idos-example-dapp/src/main.js, packages/idos-sdk-js/src/lib/crypto.js, packages/idos-sdk-js/src/lib/data.js, packages/idos-sdk-js/src/lib/index.js, packages/idos-sdk-js/src/lib/kwil-wrapper.js
Tested it against a local node with a new `has_profile` action:
```sql
action has_profile($address) public view {
SELECT EXISTS(
SELECT 1 FROM wallets WHERE address=$address COLLATE NOCASE
) AS has_profile;
}
```
=> Add `hasProfile()` and call `setSigner()`  only if needed

.github/workflows/format.yml, .prettierignore, README.md, apps/idos-enclave/src/dialog.js, apps/idos-enclave/src/enclave.js, apps/idos-enclave/src/idOSKeyDerivation.js, apps/idos-example-dapp/index.html, apps/idos-example-dapp/src/cache.js, apps/idos-example-dapp/src/main.js, apps/idos-example-dapp/src/styles.css, apps/idos-example-dapp/src/terminal.js, apps/idos-example-dapp/vite.config.ts, package.json, packages/idos-sdk-js/.eslintrc.cjs, packages/idos-sdk-js/README.md, packages/idos-sdk-js/src/__tests__/verifiable-credentials.test.js, packages/idos-sdk-js/src/lib/auth.js, packages/idos-sdk-js/src/lib/data.js, packages/idos-sdk-js/src/lib/enclave-providers/metamask-snap-enclave.js, packages/idos-sdk-js/src/lib/enclave.js, packages/idos-sdk-js/src/lib/grants/evm.js, packages/idos-sdk-js/src/lib/index.js, packages/idos-sdk-js/src/lib/kwil-wrapper.js, packages/idos-sdk-js/src/lib/nonce.js, packages/idos-sdk-js/src/lib/verifiable-credentials.js, packages/idos-sdk-js/types.d.ts, packages/idos-store/index.js
I felt the need for this to make rebases more obvious.
Ask PR. I'm pretty sure this is what we want, but I want to ask permission and avoid surprises.
=> Ensure code formatting

packages/idos-sdk-js/src/lib/index.js
Show PR. This is always the right call.
=> Throw error

packages/idos-sdk-js/src/lib/auth.js
=> Obvious mistakes

packages/idos-sdk-js/src/lib/enclave.js
Noticed while writing https://github.com/idos-network/idos-sdk-js/pull/66
Show PR.
=> Obvious typo

packages/idos-sdk-js/src/lib/grants/grants.ts
https://github.com/idos-network/idos-sdk-js/pull/73/files/8f6b720836619adbf7c4d1eea0fc3ec923996739#r1403016598
=> Add more ergonomic names

apps/idos-data-dashboard/src/connect-wallet.tsx
Let's respect their capitalization.
=> feat(dashboard): capitalize NEAR

apps/idos-enclave/src/enclave.js
Show PR, this was obviously a copy-pasta problem from `decrypt`.
=> Fix variable name

packages/idos-sdk-js/src/lib/idos.ts, packages/idos-sdk-js/src/lib/kwil-wrapper.ts
Just because I want to be able to use them in the example dApp's fake backend.
=> feat(sdk): extract kwil defaults

apps/idos-example-dapp/package.json, apps/idos-example-dapp/src/fake-server.ts, apps/idos-example-dapp/src/main.js, apps/idos-example-dapp/src/terminal.js, pnpm-lock.yaml
Things that need to get in before this:
=> feat(example-dapp,sdk): EVM grants

packages/idos-sdk-js/src/lib/idos.ts, packages/idos-sdk-js/src/lib/kwil-wrapper.ts
Extracted from https://github.com/idos-network/idos-sdk-js/pull/143
=> chore: extract KwilWrapper.init

packages/idos-sdk-js/src/lib/idos.ts
=> fix: remove double await

packages/idos-sdk-js/src/lib/idos.ts
=> chore: remove unnecessary import

packages/idos-sdk-js/src/lib/grants/evm.ts, packages/idos-sdk-js/src/lib/grants/near.ts
=> fix: better types cohesion

packages/idos-sdk-js/package.json, packages/idos-sdk-js/src/lib/idos-grantee.ts, packages/idos-sdk-js/src/lib/kwil-wrapper.ts, pnpm-lock.yaml
To take advantage of new Kwil niceties.
=> chore: better dbId and chainId discovery

packages/idos-sdk-js/src/lib/grants/grants.ts
Just removing cruft that isn't useful anymore.
```bash
$ git grep encryptedWith | wc -l
0
```
=> feat: more homogeneous Grants interface

packages/idos-sdk-js/src/lib/grants/evm.ts
=> chore: better comment

apps/idos-example-dapp/api/EVM.ts, apps/idos-example-dapp/api/NEAR.ts
Show PR.
🔨 to make it work locally and on Vercel.
=> chore: hammer crypto in

packages/idos-sdk-js/src/lib/grants/grants.ts, packages/idos-sdk-js/src/lib/idos.ts
Show PR.
Just to converge on https://github.com/idos-network/idos-sdk-js/issues/173
=> chore: rename grants init to connect

apps/idos-data-dashboard/src/core/near.tsx
Show PR.
More work for https://github.com/idos-network/idos-sdk-js/issues/173
=> chore: rename init to initialize

packages/idos-sdk-js/src/lib/idos-grantee.ts, packages/idos-sdk-js/src/lib/kwil-wrapper.ts
Show PR.
More work for https://github.com/idos-network/idos-sdk-js/issues/173
=> chore: add type annotations to init functions

apps/idos-example-dapp/src/terminal.js, packages/idos-sdk-js/src/lib/auth.ts, packages/idos-sdk-js/src/lib/enclave-providers/iframe-enclave.ts, packages/idos-sdk-js/src/lib/grants/evm.ts, packages/idos-sdk-js/src/lib/grants/near.ts, packages/idos-sdk-js/src/lib/idos.ts, packages/idos-store/index.ts
Show PR. This is the result of applying all linters with `--apply-unsafe` and manually going over the result.
All changes are expected to be cosmetic only.
=> chore: make biome happier

packages/idos-sdk-js/src/lib/grants/evm.ts, packages/idos-sdk-js/src/lib/grants/grants.ts, packages/idos-sdk-js/src/lib/grants/near.ts
Show PR for https://github.com/idos-network/idos-sdk-js/issues/173. I seem to have left this one behind.
=> chore: rename build to init

packages/idos-sdk-js/src/lib/enclave-providers/iframe-enclave.ts, packages/idos-sdk-js/src/lib/enclave-providers/interface.ts, packages/idos-sdk-js/src/lib/enclave.ts
Show PR.
Confirmed types on localhost by adding a debugger right after `await this.provider.load()`.
=> chore: correct StoredData

packages/idos-sdk-js/src/lib/kwil-wrapper.ts
=> chore: add some safeties to kwil wrapper

apps/idos-data-dashboard/src/components/proof-of-personhood.tsx, apps/idos-data-dashboard/src/vite-env.d.ts
The current approach leaves https://dashboard.playgrund.idos.network/ unable to function well.
=> chore: start by extracting the replaceable pieces

apps/idos-example-dapp/api/EVM.ts, packages/idos-sdk-js/src/__tests__/kwil-wrapper.test.ts, packages/idos-sdk-js/src/lib/auth.ts, packages/idos-sdk-js/src/lib/data.ts, packages/idos-sdk-js/src/lib/grants/near.ts, packages/idos-sdk-js/src/lib/idos-grantee.ts, packages/idos-sdk-js/src/lib/kwil-wrapper.ts
Extracted from https://github.com/idos-network/idos-sdk-js/pull/231
=> refactor: type nits

packages/idos-sdk-js/src/lib/grants/evm.ts, packages/idos-sdk-js/src/lib/grants/near.ts
Just to get some easy wins in.
=> fix: type nits

apps/idos-sdk-e2e/README.md
Just to spruce things up a bit.
=> fix: e2e docs

apps/idos-example-dapp/vite.config.ts, packages/idos-sdk-js/package.json, packages/idos-sdk-js/src/lib/grants/evm.ts, packages/idos-sdk-js/src/lib/grants/near.ts, packages/idos-sdk-js/src/lib/utils.ts, pnpm-lock.yaml
Made sure it works by clicking around in idos-example-dapp.
=> feat: optional networks

packages/idos-sdk-js/README.md
=> docs: whitespace and typo

package.json, pnpm-lock.yaml
Just because it kept complaining.
=> chore: bump turbo

apps/idos-data-dashboard/package.json, apps/idos-data-dashboard/src/connect-wallet.tsx, apps/idos-data-dashboard/src/core/wagmi.ts, apps/idos-data-dashboard/src/main.tsx, pnpm-lock.yaml
I didn't migrate the way of connection in the rest of apps (issuer and dapps dashboard) till this PR is accepted
=> feat: migrate from `web3Modal` to `reown/appkit`

turbo.json
As per https://github.com/vercel/next.js/discussions/47517#discussioncomment-11238932
=> fix: turbo caching

apps/dashboard-for-dapps/README.md, apps/dashboard-for-dapps/src/routes/__root.tsx, apps/dashboard-for-dapps/src/vite-env.d.ts, apps/dashboard-for-dapps/src/wagmi.config.ts
=> feat(dashboard-for-dapps): add wallet connect

apps/idos-enclave/src/components/ui/button.tsx, apps/idos-enclave/src/components/ui/heading.tsx, apps/idos-enclave/src/components/ui/paragraph.tsx, apps/idos-enclave/src/components/ui/text-field.tsx, apps/idos-enclave/src/lib/idOSKeyDerivation.ts, apps/idos-enclave/src/pages/recovery/PasswordOrKeyBackup.tsx, packages/kwil-actions/src/credentials.ts
=> chore: fix some typos in comment

examples/grantee-sdk-demo/src/app/page.tsx
I was tired of not being able to run `turbo build` at the root of the project.
Show PR.
=> fix(grantee-sdk-demo): don't pre-render

apps/idos-enclave/package.json, apps/idos-enclave/vite.config.ts, pnpm-lock.yaml
[REF](https://stackoverflow.com/questions/70714690/buffer-is-not-defined-in-react-vite#answer-70719923)
=> fix(enclave): add node polyfills for enclave

.github/workflows/format.yml, .github/workflows/pkg.pr.new.yml, .github/workflows/playwright-playground.yml, .github/workflows/playwright-production.yml, .github/workflows/unit-tests.yml
Just modernizing things.
Show PR.
=> chore: update ci

packages/@controllers/src/secure-enclave/metamask-snap-enclave.ts
=> fix: path typo

AI-BRIEF.md
Just something to get started. We should totally keep fine-tuning a doc like this.
Looking for opinions.
=> chore: AI instructions

packages/issuer-sdk-js/src/server/user.ts
Since there is a missing transaction, I need to call those two separately.
=> feat: individual exports for profile creation functionality

docs/glossary.md, packages/consumer-sdk-js/README.md, packages/consumer-sdk-js/src/server/idOS-grantee.ts
=> docs: first iteration on consumer sdk js

examples/consumer-and-issuer/src/app/page.tsx
Ask PR.
These operators seemed unnecessary. The type system agrees with me. Maybe there's something I'm missing?
=> fix: remove unnecessary null shortcuts

.github/workflows/pkg.pr.new.yml
=> chore: dont call pkg-pr-new twice on PRs

examples/consumer-and-issuer/src/components/onboarding.tsx, examples/passporting/src/app/api/shared-credential/[userId]/route.ts, packages/@controllers/src/isle/index.ts, packages/@core/package.json, packages/@core/src/client/index.ts, packages/@core/src/kwil-actions/grants.ts, packages/@core/src/types/index.ts, packages/consumer-sdk-js/src/server/idOS-consumer.ts, packages/consumer-sdk-js/src/server/index.ts, packages/issuer-sdk-js/src/client/user.ts
=> fix: remove dead or misused code

packages/consumer-sdk-js/src/server/index.ts
=> fix: small touch ups

apps/isle/src/features/create-profile.tsx
=> fix: switch colors

examples/pay-demo/app/routes/kyc/noah/link.ts, packages/consumer/src/index.ts
=> fix(idos#client): Fix return type of get shared credentials

packages/utils/src/enclave/types.ts
Fixing enum types after zod@4 upgrade.
=> fix(enclave#types): Enclave types enum

README.md, packages/client/README.md, packages/consumer/README.md, packages/issuer/README.md, packages/utils/README.md
https://idosgroup.slack.com/archives/C07QD1FLGU9/p1758022015638159?thread_ts=1757501981.077549&cid=C07QD1FLGU9
Ship PR.
=> Add legalities to READMEs

package.json
Because this is apparently the current panacea, according to Mo.
=> Add build:packages

packages/utils/src/enclave/local.ts
Follow-up to https://github.com/idos-network/idos-sdk-js/issues/1127
=> fix(enclave): delete old keys every time we set the new ones

packages/utils/src/enclave/keys.ts, packages/utils/src/enclave/local.ts
=> fix(enclave): more deprecation straightning

packages/issuer/src/index.ts
Follow-up to https://github.com/idos-network/idos-sdk-js/pull/1189
=> fix: expose getUser
