idos-network/idos-sdk-js

apps/idos-enclave/src/enclave.js

Show PR.
I don't know why, but sometimes I was getting messages from Metamask, and it was crashing the enclave.
It stopped crashing.

Ignore Metamask messages

---

packages/idos-sdk-js/src/lib/auth.ts
packages/idos-sdk-js/src/lib/utils.ts

We don't need to fetch a new public key from the network, we already got one from signing.

Introduce implicitAddressFromPublicKey

---

apps/idos-data-dashboard/src/core/idos.tsx
packages/idos-sdk-js/src/lib/idos.ts

- Don't use the `KwilWrapper.defaults.kwilProvider` to discover `chainId` 
- Avoid data races and stand-in values
- Use `.env` variables for the Dashboard initialisation
This already bit a user, so let's make sure we fix it.

feat: better chainId discovery

---

apps/idos-example-dapp/package.json
packages/idos-sdk-js/package.json
packages/idos-sdk-js/src/lib/kwil-wrapper.ts
pnpm-lock.yaml

So people don't have to manually clean HttpOnly cookies.

fix: log the kwil client out before using a new signer

---

packages/idos-sdk-js/src/lib/kwil-wrapper.ts

Show PR. This is super trivial.
Before:
After:

chore: add preemtive warning

---

apps/idos-example-dapp/index.html

Was there any reason we were duplicating CSS like this?

chore: use css file

---

packages/idos-sdk-js/src/lib/data.ts
packages/idos-sdk-js/src/lib/idos-grantee.ts

I think we don't need to import anything.
```bash
$ node
Welcome to Node.js v18.19.0.
Type ".help" for more information.
> crypto.getRandomValues
[Function: getRandomValues]
```
And, it's in your window too:

chore: just consider crypto exists

---

apps/idos-data-dashboard/src/routes/dashboard/wallets/components/add-wallet.tsx
packages/idos-sdk-js/src/lib/utils.ts

When it's given a non-NEAR address, it just returns null. Let's cover that case.

fix: support errors on getNearFullAccessPublicKeys

---

packages/idos-sdk-js/src/lib/data.ts
packages/idos-sdk-js/src/lib/enclave-providers/iframe-enclave.ts
packages/idos-sdk-js/src/lib/enclave-providers/interface.ts
packages/idos-sdk-js/src/lib/enclave-providers/metamask-snap-enclave.ts
packages/idos-sdk-js/src/lib/enclave.ts

Show PR for https://github.com/idos-network/idos-sdk-js/issues/173.
This one pains me a little bit. `ready` and `init` sound like synonyms. However, I really want to enforce the expectations around the name `init`, I don't have a better at hand, and this is not part of the public API.
In order to self-ship, I'll have to see this decrypting the contents of an current credential.

chore: rename init to ready

---

packages/idos-sdk-js/src/lib/auth.ts
packages/idos-sdk-js/src/lib/data.ts

Show PR.
This used to be a useful shortcut to discover `human_id` when we required a signature on every read call to Kwil. Now that we're using kgw's cookie auth, we always need a signature, and we re-use that one for all reads.
Removing this buys having less dependencies (and therefore easier-to-test things).

chore: remove `setHumanId` optimization

---

apps/idos-enclave/src/lib/enclave.js
apps/idos-enclave/src/pages/App.tsx
apps/idos-enclave/src/pages/methods/Passkey.tsx
apps/idos-example-dapp/src/main.js
packages/idos-sdk-js/src/lib/enclave-providers/iframe-enclave.ts
packages/idos-sdk-js/src/lib/enclave-providers/types.ts

* if the enclave forgot the preferred auth method but had a credential id, we were opening the popup anyway
* now we're trying to get passkey from the iframe before opening
* if the user chooses passkey in the enclave popup and it doesn't remember the credential id, we were causing passkey creation
* now, we assume one must exist and ask the user to choose from a passkey list instead
* only if none is chosen AND we're in "new user" mode do we create one
**Note:** I've seen this fail occasionally during development, where at the end of the popup journey, it wouldn't close. ~~Can't reproduce it anymore, but~~ please pay extra attention to this fact, it might ring a bell during the review.
**Edit:** the above seems to be fixed; now that the Enclave uses React, waiting for the popup's native …

feat: a more sensible enclave unlocking flow

---

packages/idos-sdk-js/src/lib/idos-grantee.ts

Adding a small missing feature so that grantees also have an ergonomic server-side way of checking their users' AGs on a chain.

feature: add getLocalAccessGrantsFromUserByAddress

---

packages/idos-sdk-js/src/lib/grants/grants.ts

Checked it manually on playground by:
- Connecting some signer (with Metamask (MM))
- Check that everything works (list grants, etc)
- Change the connected address on MM
- Called `setSigner` again
- Things still work, and show data for the new address.

feat: allow reconnections

---

packages/idos-sdk-js/src/__tests__/auth.test.ts
packages/idos-sdk-js/src/lib/auth.ts

Before:
```
Uncaught TypeError: Cannot destructure property 'current_public_key' of '(intermediate value)' as it is undefined.
```
After:
```
Uncaught NoProfile: Signer's address is not known to idOS.
```

feat(idos-sdk): raise clearer exception in auth

---

packages/idos-sdk-js/src/lib/grants/near.ts

Just because I wanted to shut up my ts warnings.
This is a mechanic change, it shouldn't change anything.

fix: tighten #sign types

---

apps/idos-enclave/src/lib/enclave.js
packages/issuer-sdk-js/README.md

---
The issue arises when the enclave store is cleared, either intentionally or unintentionally.  
---
The `humanId` value is essential as it is used as a salt in the `idosKeyDerivation` process. Without this value, the key derivation process fails, leading to the issue.  
---
1. Attempt to display content for one of your credentials.  
2. Clear the enclave's local storage after the Unlock button appears.  
3. Observe the failure when attempting to proceed.  
---
1. `storage` method is invoked as soon as the Unlock button is displayed.  
2. The `humanId` is explicitly assigned to `this.humanId` within the function block, ensuring the value remains preserved within the `Enclave` class, even if the store is cleared.  
3. As an additional safeguard, an error is thrown if the `humanId` is not …

feat: handle no `humanId` being passed at enclave dialog open

---

apps/idos-data-dashboard/index.html

In case you have less than 5 credentials. clicking on view credential and unlocking enclave won't be an issue.
but there's a problem when u have more than 5. so absolute would confuse you about location of un-lock enclave button. 
a position: fixed. fixed it

fix(data-dashboard): fix unlock button location

---

examples/issuer-sdk-demo/src/actions/index.ts

VS Code was highlighting the first `c`. I'm pretty sure this was some weird utf-8 thingy that got left behind.
Show PR.

fix: weird utf8 chars

---

packages/issuer-sdk-js/tsup.config.ts

Show PR.
```bash
pkoch@bolota:~/github.com/idos-network/idos-sdk-js/packages/issuer-sdk-js
$ pnpx publint --strict
Running publint v0.3.6 for @idos-network/issuer-sdk-js...
Packing files with `pnpm pack`...
Linting...
Errors:
1. pkg.exports["./grants"].types is ./dist/grants.d.ts but the file does not exist.
2. pkg.exports["./grants"].import is ./dist/grants.js but the file does not exist.
```

chore: add missing entry

---

packages/@core/package.json
packages/@core/src/index.ts
packages/@core/src/kwil-actions/attributes.ts
packages/@core/src/kwil-actions/credentials.ts
packages/@core/src/kwil-actions/grants.ts
packages/@core/src/kwil-actions/index.ts
packages/@core/src/kwil-actions/user.ts
packages/@core/src/kwil-actions/wallets.ts
packages/@core/src/kwil-infra/create-kwil-client.ts
packages/@core/src/kwil-infra/create-kwil-signer.ts
packages/@core/src/kwil-infra/create-near-wallet-kwil-signer.ts
packages/@core/src/kwil-infra/index.ts
packages/consumer-sdk-js/src/server/idOS-consumer.ts

cc @Mohammed-Mamoun98 
Extracting Kwil non-action methods in preparation for not exporting actions in the root, so it makes it trivial to see who's reaching for them.

feat: extract kwil infra

---

examples/consumer-and-issuer/src/components/onboarding.tsx
packages/@controllers/src/isle/index.ts
packages/@core/src/index.ts
packages/consumer-sdk-js/src/client/credentials.ts
packages/consumer-sdk-js/src/client/grants.ts
packages/consumer-sdk-js/src/client/user.ts
packages/issuer-sdk-js/src/client/user.ts
packages/issuer-sdk-js/src/server/credentials.ts
packages/issuer-sdk-js/src/server/grants.ts
packages/issuer-sdk-js/src/server/user.ts

cc @Mohammed-Mamoun98 
Force modules that use kwil-actions to import from it directly. This way, we can see what abstractions are currently leaking.

feat: dont export kwil actions on root

---

apps/passporting-server/src/core.js
examples/pay-demo/app/providers/noah.server.ts
examples/pay-demo/app/routes/app.tsx

The passporting-server was failing on Vercel with the error:
```
ReferenceError: exports is not defined in ES module scope
```
This occurred because the `ripple-keypairs` package uses CommonJS syntax (`exports`, `require`) but was being imported in an ES module context.
Replaced the static import of `ripple-keypairs` with a dynamic import to avoid the CommonJS/ES module conflict:
```javascript
// Before
import * as xrpKeypair from "ripple-keypairs";
// After  
const xrpKeypair = await import("ripple-keypairs");
```
- **File**: `apps/passporting-server/src/core.js`
- **Line**: 158 - Replaced static import with dynamic import in the XRPL signature verification logic
This fix ensures compatibility with Vercel's ES module environment while maintaining the same functionality for XRPL signature …

fix(passporting-server): dynamicly import ripple key pairs

---

packages/issuer/tsdown.config.ts

The key issue appears to be the `inlineDynamicImports: true` setting in your `tsdown.config.ts` This option was causing the bundler to absorb the ripple-keypairs code directly into your package, which re-introduced the CommonJS/ESM conflict no matter how we imported it.

fix/remove inlineDynamicImports flag from issuer tsdown.config
